import { BookOpen, Target, Users, TrendingUp } from 'lucide-react';

export const careerTopics = [
    {
        slug: 'interview-preparation',
        title: 'Interview Preparation',
        description: 'Master the art of interviewing with our comprehensive guides and mock questions.',
        icon: Users,
        color: 'bg-blue-100 text-blue-600',
        content: `
            <h2>The STAR Method</h2>
            <p>The STAR method is a structured manner of responding to a behavioral-based interview question by discussing the specific <strong>Situation, Task, Action, and Result</strong> of the situation you are describing.</p>
            <ul>
                <li><strong>Situation:</strong> Describe the context within which you performed a job or faced a challenge at work. Be specific.</li>
                <li><strong>Task:</strong> Next, describe your responsibility in that situation.</li>
                <li><strong>Action:</strong> You then describe how you completed the task or endeavored to meet the challenge. Focus on what <em>you</em> did, rather than what your team, boss, or coworker did.</li>
                <li><strong>Result:</strong> Finally, explain the outcomes or results generated by the action taken. Whenever possible, quantify your success (e.g., "increased sales by 20%").</li>
            </ul>

            <h2>Top 5 Most Common Interview Questions</h2>
            <p>While every interview is unique, certain questions appear frequently across all industries. Prepare answers for these:</p>
            <ol>
                <li><strong>"Tell me about yourself."</strong> Keep this professional. Focus on your current role, your past experiences that led you here, and why you are excited about this specific opportunity.</li>
                <li><strong>"What is your greatest weakness?"</strong> Choose a minor weakness that is an actual area for improvement (not "I work too hard"), and explain the steps you are actively taking to overcome it.</li>
                <li><strong>"Why do you want to work here?"</strong> This tests your research. Have specific reasons related to their product, culture, or recent news.</li>
                <li><strong>"Describe a time you had a conflict with a coworker."</strong> Focus on resolution and emotional intelligence, not the drama of the conflict itself.</li>
                <li><strong>"Where do you see yourself in five years?"</strong> Be ambitious but realistic, and ensure your answer aligns with the trajectory of the role you are applying for.</li>
            </ol>

            <h2>Questions to Ask the Interviewer</h2>
            <p>An interview is a two-way street. When they ask "Do you have any questions for me?", never say no. Have 3-5 thoughtful questions prepared. Examples include:</p>
            <ul>
                <li>"What does a typical day look like in this role?"</li>
                <li>"How does the team measure success?"</li>
                <li>"What are the biggest challenges facing the department right now?"</li>
                <li>"What are the opportunities for professional development here?"</li>
            </ul>
        `
    },
    {
        slug: 'career-advancement',
        title: 'Career Advancement',
        description: 'Strategies for getting promoted, asking for raises, and managing your career trajectory.',
        icon: TrendingUp,
        color: 'bg-emerald-100 text-emerald-600',
        content: `
            <h2>Document Your Wins</h2>
            <p>Your manager is busy and likely won't remember everything you accomplish throughout the year. It's your responsibility to maintain a "brag document." Keep a running list of your major projects, the impact they had (quantified if possible), compliments from stakeholders, and times you went above and beyond your job description. This document becomes the foundation for your performance review and promotion requests.</p>

            <h2>How to Ask for a Promotion</h2>
            <p>Don't wait for your annual review to spring a promotion request on your boss. It should be an ongoing conversation.</p>
            <ul>
                <li><strong>Set the goal early:</strong> Tell your manager, "My goal is to reach Senior Level within the next 12-18 months. What milestones do I need to hit to get there?"</li>
                <li><strong>Check in consistently:</strong> Use your 1-on-1s to review progress against those milestones.</li>
                <li><strong>Make the case:</strong> When it's time to formally ask, present your brag document. Frame the conversation around the value you bring to the company, not why you personally need more money.</li>
            </ul>

            <h2>Mastering the "Managing Up" Technique</h2>
            <p>Managing up doesn't mean telling your boss what to do; it means understanding their goals, communication style, and pressures, and adjusting your approach to make their life easier. Anticipate their needs, come to them with solutions (not just problems), and communicate exactly how they prefer (email, Slack, brief in-person chats).</p>

            <h2>Building Your Internal Network</h2>
            <p>Advancement often requires cross-functional visibility. Volunteer for committees, attend optional company events, and schedule "virtual coffees" with people in departments you interact with but don't know well. Having champions outside of your direct management chain is invaluable during promotion evaluation periods.</p>
        `
    },
    {
        slug: 'resume-cover-letter-tips',
        title: 'Resume & Cover Letter Tips',
        description: 'Learn how to craft compelling documents that showcase your unique value.',
        icon: BookOpen,
        color: 'bg-purple-100 text-purple-600',
        content: `
            <h2>The Purpose of the Cover Letter</h2>
            <p>Your resume tells them <em>what</em> you did. Your cover letter tells them <em>why</em> it matters to them. It's not a narrative regurgitation of your resume. Instead, use the cover letter to connect the dots between their specific pain points (found in the job description) and your proven ability to solve those problems.</p>

            <h2>Anatomy of a Modern Cover Letter</h2>
            <p>Keep it brevity. A cover letter should rarely exceed one page.</p>
            <ul>
                <li><strong>The Hook:</strong> Open strong. Instead of "I am writing to apply for...", start with a bold statement about your experience or a connection to their recent company news.</li>
                <li><strong>The Body (The 'Why You'):</strong> Select 1-2 major accomplishments from your resume and expand on them, specifically tying them to the requirements of the role.</li>
                <li><strong>The 'Why Them':</strong> Briefly explain why you want to work for <em>this specific company</em>. What about their mission or culture resonates with you?</li>
                <li><strong>The Call to Action:</strong> Close confidently, reiterating your enthusiasm and outlining the next steps.</li>
            </ul>

            <h2>Action Verbs Give Your Resume Power</h2>
            <p>Avoid passive phrases like "Responsible for" or "Tasked with." Start every bullet point on your resume with a strong action verb. Examples:</p>
            <ul>
                <li>Instead of "Was in charge of a team," use <strong>"Orchestrated a cross-functional team of 10..."</strong></li>
                <li>Instead of "Made the process faster," use <strong>"Streamlined the onboarding process, reducing completion time by 40%..."</strong></li>
                <li>Instead of "Helped with sales," use <strong>"Spearheaded a new outreach initiative that generated..."</strong></li>
            </ul>

            <h2>The "One Page" Resume Rule: Fact or Fiction?</h2>
            <p>It's generally a good guideline, but not a hard rule. If you have less than 10 years of experience, you should aim for one page to force yourself to be concise. However, if you are a senior executive or have extensive academic/publication history, expanding to two pages is completely acceptable and often necessary. Never go beyond two pages unless you are writing an academic CV.</p>
        `
    },
    {
        slug: 'job-search-strategies',
        title: 'Job Search Strategies',
        description: 'Navigate the modern job market with effective networking and application tactics.',
        icon: Target,
        color: 'bg-orange-100 text-orange-600',
        content: `
            <h2>The "Hidden" Job Market</h2>
            <p>It's estimated that up to 70% of open positions are never publicly advertised. These roles are filled internally, through employee referrals, or by recruiters reaching out directly to passive candidates. To tap into this hidden market, you must move beyond just submitting online applications.</p>

            <h2>Networking: Quality Over Quantity</h2>
            <p>Networking isn't about collecting hundreds of business cards or LinkedIn connections. It's about building genuine relationships.</p>
            <ul>
                <li><strong>Informational Interviews:</strong> Reach out to people holding roles you aspire to. Ask for 15 minutes of their time not to ask for a job, but to ask for their advice and hear about their career path.</li>
                <li><strong>Alumni Networks:</strong> Your university alumni network is one of the warmest entry points you have. Use LinkedIn to find alumni working at companies you are targeting.</li>
                <li><strong>Professional Associations:</strong> Join industry-specific groups (both online and local chapters) to meet peers and stay updated on industry trends.</li>
            </ul>

            <h2>Optimizing Your LinkedIn Profile</h2>
            <p>Recruiters live on LinkedIn. Make sure your profile is optimized to be found:</p>
            <ul>
                <li><strong>Headline:</strong> Don't just list your current title. Add your core skills or the value you provide (e.g., "Senior Financial Analyst | Specializing in SaaS Revenue Modeling & Forecasting").</li>
                <li><strong>Summary (About Section):</strong> Write this in the first person. Tell your professional story, highlight your biggest wins, and state what you are passionate about mechanically.</li>
                <li><strong>Skills:</strong> Pin your top 3 skills and ensure they align with the roles you are applying for. Endorsements help, but the presence of the keywords is most important for search visibility.</li>
            </ul>

            <h2>Organizing Your Search</h2>
            <p>Treat your job search like a project. Use tools like Excel, Notion, or dedicated job search trackers to log where you've applied, the date you applied, the status, and when you need to follow up. Following up one week after an application or interview demonstrates continued interest and professionalism.</p>
        `
    }
];
